CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE MACHINE
(
  ID         BIGINT  NOT NULL,
  CREATED_AT TIMESTAMP(6) WITHOUT TIME ZONE,
  DELETED    BOOLEAN NOT NULL,
  NAME       CHARACTER VARYING(255),
  UPDATED_AT TIMESTAMP(6) WITHOUT TIME ZONE,
  PRIMARY KEY (ID)
);
