logging:
  level:
    root: info
server:
  port: 1980
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: bimbam
    url: jdbc:postgresql://localhost:1112/dictionary
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: dictionary
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  thymeleaf:
    cache: false

